minor improvements

diff --git a/etc/initramfs-tools/hooks/boundbox b/etc/initramfs-tools/hooks/boundbox
--- a/etc/initramfs-tools/hooks/boundbox
+++ b/etc/initramfs-tools/hooks/boundbox
@@ -36,29 +36,29 @@ esac
 . /usr/share/initramfs-tools/hook-functions
 
 die() {
-    code="$1"
-    msg="$2"
-    echo "    (ERROR): $msg" >&2
-    exit $1
+  code="$1"
+  msg="$2"
+  echo "Ooops: $msg" >&2
+  exit $code
 }
 
 find_binary() {
-    bin_name="$1"
-    resolved=$(command -v ${bin_name})
-    [ -z "$resolved" ] && die 1 "Unable to find ${bin_name}"
-    echo "$resolved"
+  bin_name="$1"
+  resolved=$(command -v "${bin_name}")
+  [ -z "$resolved" ] && die 1 "Unable to find ${bin_name}"
+  echo "$resolved"
 }
 
 for f in /sbin/cryptsetup /lib/cryptsetup/askpass; do
-    if [ ! -e "${DESTDIR}${f}" ]; then
-        die 2 "cryptsetup utility '$f' wasn't found in the generated ramdisk image. "
-    fi
+  if [ ! -e "${DESTDIR}${f}" ]; then
+    die 2 "cryptsetup utility '$f' wasn't found in the generated ramdisk image. "
+  fi
 done  
 
 for f in /etc/boundbox/initramfs/key /etc/boundbox/initramfs/known_hosts; do
-    if [ ! -f "${f}" ]; then
-        die 2 "no '${f} was found"
-    fi
+  if [ ! -f "${f}" ]; then
+    die 2 "no '${f} was found"
+  fi
 done
 
 mkdir -p "$DESTDIR/etc/boundbox"
@@ -68,7 +68,7 @@ copy_file data "/etc/boundbox/initramfs/known_hosts" "/etc/boundbox"
 ssh-keygen -E SHA256 -lf "/etc/boundbox/initramfs/key" | grep -oP 'SHA256:[a-zA-Z0-9+=/]+' > "$DESTDIR/etc/boundbox/login"
 
 for f in $(find_binary "ssh") $(find_binary "grep") $(find_binary "sed") $(find_binary "awk"); do
-    copy_exec "${f}" || die 2 "Unable to copy ${f} to initrd image"
+  copy_exec "${f}" || die 2 "Unable to copy ${f} to initrd image"
 done
 
 # Copy latest versions of shared objects needed for DNS resolution
diff --git a/etc/initramfs-tools/scripts/local-bottom/boundbox b/etc/initramfs-tools/scripts/local-bottom/boundbox
--- a/etc/initramfs-tools/scripts/local-bottom/boundbox
+++ b/etc/initramfs-tools/scripts/local-bottom/boundbox
@@ -23,14 +23,14 @@
 PREREQ=""
 
 prereqs() {
-    echo "$PREREQ"
+  echo "$PREREQ"
 }
 
 case "$1" in
-    prereqs)
-        prereqs
-        exit 0
-    ;;
+  prereqs)
+    prereqs
+    exit 0
+  ;;
 esac
 
 [ -s /run/boundbox.pid ] || exit 0
@@ -38,25 +38,25 @@ esac
 set -e
 
 if [ -e /etc/boundbox/boundbox.conf ]; then
-    . /etc/boundbox/boundbox.conf
+  . /etc/boundbox/boundbox.conf
 fi
 . /scripts/functions
 
 pid=$(cat /run/boundbox.pid)
 child_pids="$({ ps -o pid,ppid 2>/dev/null || ps -l ||
-    { echo 'boundbox: unable to get list of processes' >&2; exit 1; }; } |
-    awk -v pid="$pid" '
-        NR==1 {
-            for (i=1; i<=NF; i++) if ($i == "PID") pid_col = i; else if ($i == "PPID") ppid_col = i
-            if (!pid_col || !ppid_col) { print "boundbox: unable to find PID and/or PPID columns in ps output" | "cat >&2"; exit 1 }
-            next
-        }
-        { if ($ppid_col == pid) print $pid_col }')"
+  { echo 'boundbox: unable to get list of processes' >&2; exit 1; }; } |
+  awk -v pid="$pid" '
+    NR==1 {
+      for (i=1; i<=NF; i++) if ($i == "PID") pid_col = i; else if ($i == "PPID") ppid_col = i
+      if (!pid_col || !ppid_col) { print "boundbox: unable to find PID and/or PPID columns in ps output" | "cat >&2"; exit 1 }
+      next
+    }
+    { if ($ppid_col == pid) print $pid_col }')"
 
 log_begin_msg "Stopping BoundBox"
 
 for kill_pid in $pid $child_pids; do
-    kill -TERM "$kill_pid" 2>/dev/null
+  kill -TERM "$kill_pid" 2>/dev/null
 done
 
 rm -f /run/boundbox.pid
@@ -66,13 +66,13 @@ log_end_msg
 # during the actual boot. Might make this configurable later if needed.
 
 if [ "$BOOT" != nfs ] && [ "$IFDOWN" != none ]; then
-    for IFACE in /sys/class/net/$IFDOWN; do
-        [ -e "$IFACE" ] || continue
-        IFACE="${IFACE#/sys/class/net/}"
-        log_begin_msg "Bringing down $IFACE"
-        ip link    set   dev "$IFACE" down
-        ip address flush dev "$IFACE"
-        ip route   flush dev "$IFACE"
-        log_end_msg
-    done
+  for IFACE in /sys/class/net/$IFDOWN; do
+    [ -e "$IFACE" ] || continue
+    IFACE="${IFACE#/sys/class/net/}"
+    log_begin_msg "Bringing down $IFACE"
+    ip link    set   dev "$IFACE" down
+    ip address flush dev "$IFACE"
+    ip route   flush dev "$IFACE"
+    log_end_msg
+  done
 fi
